# tasks 12 july 

## task 1 

In [6]:
import numpy as np

In [7]:
arr = np.arange(1, 11)

In [8]:
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

Array: [ 1  2  3  4  5  6  7  8  9 10]
Sum: 55
Mean: 5.5
Minimum: 1
Maximum: 10


## task 2 

In [16]:
arr = np.random.randint(1, 21, size=(4, 4))

print("Array:")
print(arr)

Array:
[[11 19  7 17]
 [ 8 17 14 14]
 [ 6  3 12  2]
 [18  7 11  6]]


In [17]:
print("Shape:", arr.shape)

print("Number of dimensions:", arr.ndim)

print("Data type:", arr.dtype)

Shape: (4, 4)
Number of dimensions: 2
Data type: int32


## task 3

In [12]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [13]:
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)

Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]


In [14]:
concat_rows = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along rows:")
print(concat_rows)

Concatenated along rows:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
concat_cols = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along columns:")
print(concat_cols)

Concatenated along columns:
[[1 2 5 6]
 [3 4 7 8]]


## task 4

In [18]:
arr = np.arange(1, 6)

In [19]:
print("Original array:", arr)

Original array: [1 2 3 4 5]


In [23]:
mult_2 = arr * 2
print("Multiplied by 2:", mult_2)

Multiplied by 2: [ 2  4  6  8 10]


In [24]:
add_5 = arr + 5
print("Added 5:", add_5)


Added 5: [ 6  7  8  9 10]
Squared: [ 1  4  9 16 25]


In [25]:
squared = arr ** 2
print("Squared:", squared)

Squared: [ 1  4  9 16 25]


## task 5

In [27]:
arr = np.arange(1, 7).reshape(2, 3)

In [28]:
print("Original array:")
print(arr)

Original array:
[[1 2 3]
 [4 5 6]]


In [29]:
add_10 = arr + 10
print("Added 10:")
print(add_10)

Added 10:
[[11 12 13]
 [14 15 16]]


In [30]:
mult_3 = arr * 3
print("Multiplied by 3:")
print(mult_3)

Multiplied by 3:
[[ 3  6  9]
 [12 15 18]]


## task 6

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [32]:
print("Array:")
print(arr)

print("Sum:", np.sum(arr))

print("Mean:", np.mean(arr))

print("Standard deviation:", np.std(arr))

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum: 45
Mean: 5.0
Standard deviation: 2.581988897471611


## task 7

In [36]:
arr = np.random.rand(10)

print("Original array:", arr)

Original array: [0.11430625 0.72479189 0.8854303  0.11735781 0.6409762  0.7755005
 0.61108773 0.39415973 0.4826453  0.06250349]


In [37]:
sorted_asc = np.sort(arr)
print("Sorted in ascending order:", sorted_asc)

Sorted in ascending order: [0.06250349 0.11430625 0.11735781 0.39415973 0.4826453  0.61108773
 0.6409762  0.72479189 0.7755005  0.8854303 ]
Sorted in descending order: [0.8854303  0.7755005  0.72479189 0.6409762  0.61108773 0.4826453
 0.39415973 0.11735781 0.11430625 0.06250349]


In [38]:
sorted_desc = np.sort(arr)[::-1]
print("Sorted in descending order:", sorted_desc)

Sorted in descending order: [0.8854303  0.7755005  0.72479189 0.6409762  0.61108773 0.4826453
 0.39415973 0.11735781 0.11430625 0.06250349]


# end of all the tasks