# task1 

In [1]:
message = "Hello World"
print(message)

Hello World


# task 2 

In [2]:
n1= 4
n2= 7

product = n1*n2
print(product)

28


# task 3

In [8]:
veg = ["carret", "onion", "salad", "potato" ]
print(veg)

['carret', 'onion', 'salad', 'potato']


# task 4 

In [9]:
#add to list 
veg.append("tomato")
veg

['carret', 'onion', 'salad', 'potato', 'tomato']

In [10]:
# drop from list
veg.remove("carret")
veg

['onion', 'salad', 'potato', 'tomato']

# task 5

In [15]:
str1 = "Hello"
str2 = "World"
result = str1 +" "+ str2
print(result) 


Hello World


# task 6

In [3]:
# print a loop in python
num = [2,3,4,5,6,5,6,8,8,8]

for a in num:
    print("numers in a list", a)

numers in a list 2
numers in a list 3
numers in a list 4
numers in a list 5
numers in a list 6
numers in a list 5
numers in a list 6
numers in a list 8
numers in a list 8
numers in a list 8


In [6]:
for a in range(1,11):
    print(a)

1
2
3
4
5
6
7
8
9
10


In [8]:
import numpy as np

num = np.random.randint(10, size=(5))
sum=0

print(num)
for n in num:
    sum = sum+n
    
print("sum is equal to " ,sum)

[9 5 0 1 8]
sum is equal to  23


In [11]:
import numpy as np

num = np.random.randint(-10,10, size=(5))
sub=0

print(num)
for n in num:
    sub = sub-n
    
print("sub is equal to " ,sub)

[-6 -6 -1  3  7]
sub is equal to  3


In [12]:
import numpy as np

num = np.random.randint(-10,10, size=(5))
pro=1

print(num)
for n in num:
    pro = pro*n
    
print("product is equal to " ,pro)

[  2   2  -7   7 -10]
product is equal to  1960


In [13]:
import numpy as np

num = np.random.randint(10, size=(5))
sum=0

print(num)
for n in num:
    sum = sum+n
    
print("sum is equal to " ,sum)
print("average is equal to " ,sum/5)

[6 6 7 4 2]
sum is equal to  25
average is equal to  5.0
